### ISSUE TITLE
Colors that identify what bins are used in the rec field analysis

### ISSUE THREAD

**Issue by garyhwbl** [Neurorobtics/Tilt-Project#6]
**Is your feature request related to a problem? Please describe.**
It is difficult to understand visually how the rec field analysis was performed on a given neuron. 

**Describe the solution you'd like**
I'd like the plotting functions to color the bins that were used in the rec field analysis (i.e. what bins are used to calculate response magnitude), as well as identifying markers (FBL, FBL, peak, etc) to show what bins were used to calculate these features. 

**Describe alternatives you've considered**

**Additional context**

**Comment by mstickle** [comment]
See comments in the graph issue. When receptive field is plotted, the area between first and last bin latency are colored red now.
